services:

  store-db:
    container_name: store-db
    image: mysql:latest
    environment:
      MYSQL_USER_NAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store-db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3309:3306
    networks:
      - store-net
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6380:6379
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis:/data
    networks:
      - store-net
    depends_on:
      - store-db
  
  keycloak:
    container_name: keycloak-butik
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - store-net
    command: 
      - "start-dev"
    depends_on:
      - store-db
  
  os-api:
    container_name: os-api
    image: os/os-api:1.0.14
    ports:
      - 8082:8080
    depends_on:
      - store-db
    networks:
      - store-net
  
  os-ui:
    container_name: os-ui
    image: os/os-ui:1.0.1
    ports:
      - 8081:80
    networks:
      - store-net
    depends_on:
      - os-api
  
networks:
  store-net:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local