services:

  store-db:
    container_name: store-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: store-db
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3309:3306
    networks:
      - store-net
    restart: unless-stopped

  store-redis:
    container_name: store-redis
    image: redis:latest
    ports:
      - 6380:6379
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis:/data
    networks:
      - store-net
  
  keycloak:
    container_name: keycloak-butik
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - store-net
    command: 
      - "start-dev"
  
networks:
  store-net:
    driver: bridge

volumes:
  mysql:
    driver: local
  redis:
    driver: local